// Generated by backend/tools/export_safety_keywords.py — do not edit.
// The canonical list lives in backend/safety.py; a test fails if this
// file drifts from it.
//
// Used ONLY when the request itself fails. The server runs the real gate;
// this errs toward showing urgent help rather than an AI answer.

export const OFFLINE_RED_PHRASES: readonly string[] = [
  "heavy bleeding",
  "bleeding heavily",
  "wont stop bleeding",
  "cannot stop bleeding",
  "gushing blood",
  "lot of blood",
  "so much blood",
  "severe bleeding",
  "soaking a pad",
  "soaking pads",
  "filling a pad",
  "bahut khoon",
  "khoon bah raha",
  "chest pain",
  "chest hurts",
  "cant breathe",
  "cannot breathe",
  "trouble breathing",
  "struggling to breathe",
  "saans nahi",
  "severe pain",
  "unbearable pain",
  "worst headache",
  "vision blur",
  "blurred vision",
  "blurry vision",
  "seeing spots",
  "flashing lights",
  "fainted",
  "passed out",
  "seizure",
  "convulsion",
  "water broke",
  "water breaking",
  "kill myself",
  "end my life",
  "end it all",
  "suicidal",
  "want to die",
  "hurt myself",
  "harm myself",
  "hurting myself",
  "harming myself",
  "harm my baby",
  "hurt my baby",
  "hurt the baby",
  "overdose",
  "cant go on",
  "dont want to be here",
  "no reason to live",
];

/** Apostrophes removed and punctuation collapsed, so "cant breathe"
 *  matches an entry written without one — which is how people type. */
export function normaliseForSafety(message: string): string {
  return message
    .toLowerCase()
    .replace(/['’ʼ`]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function looksUrgentOffline(message: string): boolean {
  const m = normaliseForSafety(message);
  return OFFLINE_RED_PHRASES.some((p) => m.includes(p));
}
