"""Generate the clients' offline red-flag lists from the backend's.

There were three lists: the server's, the web app's and Android's. The clients'
were copies made once and never revisited, so widening the server's — which is
what today's fix did — left both clients screening the OLD, narrower set while
offline. That is the exact shape of the defect being fixed, sitting in two more
places.

The clients cannot call the API in the situation their list exists for, so they
must ship one. This makes that copy a build artifact rather than a fork:
`python tools/export_safety_keywords.py` rewrites both, and a test fails if the
checked-in files have drifted from safety.py.

Only the RED phrases are exported. Amber changes nothing a client does offline,
and the regex patterns would need two more implementations to keep honest.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

import safety  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
BANNER = ("// Generated by backend/tools/export_safety_keywords.py — do not edit.\n"
          "// The canonical list lives in backend/safety.py; a test fails if this\n"
          "// file drifts from it.\n")


def web_source() -> str:
    entries = ",\n".join(f'  "{p}"' for p in safety.RED_PHRASES)
    return (
        BANNER
        + "//\n"
        + "// Used ONLY when the request itself fails. The server runs the real gate;\n"
        + "// this errs toward showing urgent help rather than an AI answer.\n\n"
        + "export const OFFLINE_RED_PHRASES: readonly string[] = [\n"
        + entries
        + ",\n];\n\n"
        + "/** Apostrophes removed and punctuation collapsed, so \"cant breathe\"\n"
        + " *  matches an entry written without one — which is how people type. */\n"
        + "export function normaliseForSafety(message: string): string {\n"
        + "  return message\n"
        + "    .toLowerCase()\n"
        + "    .replace(/['\u2019\u02bc`]/g, \"\")\n"
        + "    .replace(/[^a-z0-9]+/g, \" \")\n"
        + "    .trim();\n"
        + "}\n\n"
        + "export function looksUrgentOffline(message: string): boolean {\n"
        + "  const m = normaliseForSafety(message);\n"
        + "  return OFFLINE_RED_PHRASES.some((p) => m.includes(p));\n"
        + "}\n"
    )


def android_source() -> str:
    entries = ",\n".join(f'        "{p}"' for p in safety.RED_PHRASES)
    return (
        "package com.aira.companion.data\n\n"
        + BANNER
        + "//\n"
        + "// Used ONLY when the request itself fails. The server runs the real gate;\n"
        + "// this errs toward showing urgent help rather than an AI answer.\n\n"
        + "object SafetyKeywords {\n"
        + "    val OFFLINE_RED_PHRASES = listOf(\n"
        + entries
        + ",\n    )\n\n"
        + "    /** Apostrophes removed and punctuation collapsed, so \"cant breathe\"\n"
        + "     *  matches an entry written without one — which is how people type. */\n"
        + "    fun normalise(message: String): String =\n"
        + "        message.lowercase()\n"
        + "            .replace(Regex(\"[\u2019\u02bc'`]\"), \"\")\n"
        + "            .replace(Regex(\"[^a-z0-9]+\"), \" \")\n"
        + "            .trim()\n\n"
        + "    fun looksUrgent(message: String): Boolean {\n"
        + "        val m = normalise(message)\n"
        + "        return OFFLINE_RED_PHRASES.any { m.contains(it) }\n"
        + "    }\n"
        + "}\n"
    )


TARGETS = {
    ROOT / "apps" / "web" / "app" / "safety-keywords.ts": web_source,
    ROOT / "apps" / "android" / "app" / "src" / "main" / "java" / "com" / "aira"
         / "companion" / "data" / "SafetyKeywords.kt": android_source,
}


def main() -> int:
    for path, build in TARGETS.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(build(), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
