// AUTO-DERIVED from Aira-Video-Topic-Catalog (catalog v1.0.0). Interim seed data
// for the Learn UI until the backend serves GET /v1/videos. Do not hand-edit —
// regenerate from the catalog. Videos are topics only (no media produced yet):
// the UI shows the library and an honest "in production" state for playback.

export type VideoJourney = "trying" | "pregnant" | "postpartum";
export type VideoSafety = "standard" | "clinical" | "urgent";
export type VideoTiming = { type: "gestational_week" | "on_demand"; startWeek?: number; endWeek?: number };
export type VideoTopic = {
  id: string; slug: string; title: string;
  category: string; categoryLabel: string;
  journeys: VideoJourney[]; timing: VideoTiming;
  format: string; minSec: number; maxSec: number;
  description: string; safety: VideoSafety;
  actions: string[]; languages: string[];
};

export const VIDEO_CATEGORIES: { key: string; label: string }[] = [
  { key: "pregnancy_week_by_week", label: "Week by week" },
  { key: "pregnancy_symptoms", label: "Symptoms" },
  { key: "nutrition", label: "Nutrition" },
  { key: "movement_and_wellness", label: "Movement & wellness" },
  { key: "tests_and_appointments", label: "Tests & appointments" },
  { key: "labour_and_delivery", label: "Labour & delivery" },
  { key: "postpartum_recovery", label: "Postpartum recovery" },
  { key: "newborn_care", label: "Newborn care" },
];

export const VIDEO_TOPICS: VideoTopic[] = [
  { id: "preg-week-04", slug: "pregnancy-week-4-beginning-the-journey", title: "Pregnancy Week 4: Beginning the Journey", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 4, "endWeek": 4}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Early pregnancy changes, confirming pregnancy and the first gentle next steps.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-05", slug: "pregnancy-week-5-early-development-and-new-changes", title: "Pregnancy Week 5: Early Development and New Changes", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 5, "endWeek": 5}, format: "weekly_update", minSec: 120, maxSec: 240, description: "What early development may look like and how the mother may begin to feel.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-06", slug: "pregnancy-week-6-managing-early-symptoms", title: "Pregnancy Week 6: Managing Early Symptoms", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 6, "endWeek": 6}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Common early symptoms, hydration and when symptoms need professional attention.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-07", slug: "pregnancy-week-7-nausea-fatigue-and-daily-care", title: "Pregnancy Week 7: Nausea, Fatigue and Daily Care", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 7, "endWeek": 7}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Practical ways to organise daily care while energy and appetite may fluctuate.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-08", slug: "pregnancy-week-8-preparing-for-the-first-visits", title: "Pregnancy Week 8: Preparing for the First Visits", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 8, "endWeek": 8}, format: "weekly_update", minSec: 120, maxSec: 240, description: "What to record, what to bring and useful questions for an early prenatal appointment.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-09", slug: "pregnancy-week-9-nutrition-without-overwhelm", title: "Pregnancy Week 9: Nutrition Without Overwhelm", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 9, "endWeek": 9}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A simple approach to meals, hydration and supplements discussed with the care team.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-10", slug: "pregnancy-week-10-your-body-and-baby-this-week", title: "Pregnancy Week 10: Your Body and Baby This Week", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 10, "endWeek": 10}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A calm overview of maternal changes and medically reviewed fetal development.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-11", slug: "pregnancy-week-11-understanding-screening-conversations", title: "Pregnancy Week 11: Understanding Screening Conversations", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 11, "endWeek": 11}, format: "weekly_update", minSec: 120, maxSec: 240, description: "How to prepare for discussions about optional prenatal screening and testing.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-12", slug: "pregnancy-week-12-closing-the-first-trimester", title: "Pregnancy Week 12: Closing the First Trimester", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 12, "endWeek": 12}, format: "weekly_update", minSec: 120, maxSec: 240, description: "What may change near the end of the first trimester and what to discuss at the next visit.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-13", slug: "pregnancy-week-13-entering-a-new-trimester", title: "Pregnancy Week 13: Entering a New Trimester", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 13, "endWeek": 13}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A transition guide covering energy, symptoms, movement and upcoming care.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-14", slug: "pregnancy-week-14-gentle-movement-and-comfort", title: "Pregnancy Week 14: Gentle Movement and Comfort", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 14, "endWeek": 14}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Safe movement questions, posture and ways to respond to changing comfort needs.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-15", slug: "pregnancy-week-15-body-changes-with-confidence", title: "Pregnancy Week 15: Body Changes With Confidence", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 15, "endWeek": 15}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Normal body changes, emotional wellbeing and questions worth saving for a visit.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-16", slug: "pregnancy-week-16-movement-awareness-begins", title: "Pregnancy Week 16: Movement Awareness Begins", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 16, "endWeek": 16}, format: "weekly_update", minSec: 120, maxSec: 240, description: "How early fetal movement may be described and why experiences differ between pregnancies.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-17", slug: "pregnancy-week-17-sleep-posture-and-daily-energy", title: "Pregnancy Week 17: Sleep, Posture and Daily Energy", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 17, "endWeek": 17}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Supporting sleep and comfort as the body continues to change.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-18", slug: "pregnancy-week-18-preparing-for-the-anatomy-scan", title: "Pregnancy Week 18: Preparing for the Anatomy Scan", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 18, "endWeek": 18}, format: "weekly_update", minSec: 120, maxSec: 240, description: "What an anatomy scan is designed to review and how to prepare questions.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-19", slug: "pregnancy-week-19-growth-nutrition-and-hydration", title: "Pregnancy Week 19: Growth, Nutrition and Hydration", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 19, "endWeek": 19}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A mother-first guide to nutrition, hydration and changing energy needs.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-20", slug: "pregnancy-week-20-the-halfway-check-in", title: "Pregnancy Week 20: The Halfway Check-In", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 20, "endWeek": 20}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A reflective check-in covering body, baby, emotions and the next appointment.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-21", slug: "pregnancy-week-21-common-discomforts-and-support", title: "Pregnancy Week 21: Common Discomforts and Support", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 21, "endWeek": 21}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Recognising common discomforts and knowing when to contact the care team.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-22", slug: "pregnancy-week-22-noticing-movement-patterns", title: "Pregnancy Week 22: Noticing Movement Patterns", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 22, "endWeek": 22}, format: "weekly_update", minSec: 120, maxSec: 240, description: "An introduction to becoming familiar with the baby's individual movement pattern.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-23", slug: "pregnancy-week-23-hydration-cramps-and-rest", title: "Pregnancy Week 23: Hydration, Cramps and Rest", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 23, "endWeek": 23}, format: "weekly_update", minSec: 120, maxSec: 240, description: "How hydration, rest and symptom notes can support a useful care conversation.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-24", slug: "pregnancy-week-24-movement-energy-and-visit-preparation", title: "Pregnancy Week 24: Movement, Energy and Visit Preparation", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 24, "endWeek": 24}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A personalised weekly update focused on maternal energy, movement and appointment questions.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-25", slug: "pregnancy-week-25-preparing-for-glucose-screening", title: "Pregnancy Week 25: Preparing for Glucose Screening", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 25, "endWeek": 25}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A plain-language introduction to glucose screening and care-team instructions.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-26", slug: "pregnancy-week-26-fatigue-iron-and-care-questions", title: "Pregnancy Week 26: Fatigue, Iron and Care Questions", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 26, "endWeek": 26}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Why persistent fatigue deserves discussion and how to prepare useful questions.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-27", slug: "pregnancy-week-27-preparing-for-the-third-trimester", title: "Pregnancy Week 27: Preparing for the Third Trimester", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 27, "endWeek": 27}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A simple review of upcoming care, practical planning and emotional wellbeing.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-28", slug: "pregnancy-week-28-movement-awareness-and-appointments", title: "Pregnancy Week 28: Movement Awareness and Appointments", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 28, "endWeek": 28}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Fetal movement awareness, common appointments and personalised reminders.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-29", slug: "pregnancy-week-29-sleep-heartburn-and-comfort", title: "Pregnancy Week 29: Sleep, Heartburn and Comfort", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 29, "endWeek": 29}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Comfort-focused strategies to discuss with the care team when sleep or heartburn is difficult.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-30", slug: "pregnancy-week-30-growth-and-birth-planning", title: "Pregnancy Week 30: Growth and Birth Planning", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 30, "endWeek": 30}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Beginning informed birth-preference discussions without creating pressure.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-31", slug: "pregnancy-week-31-swelling-comfort-and-warning-signs", title: "Pregnancy Week 31: Swelling, Comfort and Warning Signs", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 31, "endWeek": 31}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Understanding common swelling while clearly identifying signs needing urgent assessment.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-32", slug: "pregnancy-week-32-baby-position-and-practical-preparation", title: "Pregnancy Week 32: Baby Position and Practical Preparation", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 32, "endWeek": 32}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A reviewed explanation of fetal position and practical preparation for later pregnancy.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-33", slug: "pregnancy-week-33-building-the-hospital-bag", title: "Pregnancy Week 33: Building the Hospital Bag", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 33, "endWeek": 33}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A calm, customisable hospital-bag checklist for mother, baby and partner.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-34", slug: "pregnancy-week-34-recognising-possible-preterm-labour", title: "Pregnancy Week 34: Recognising Possible Preterm Labour", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 34, "endWeek": 34}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Clear signs that require prompt contact with the maternity care team.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-35", slug: "pregnancy-week-35-late-pregnancy-tests-and-decisions", title: "Pregnancy Week 35: Late-Pregnancy Tests and Decisions", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 35, "endWeek": 35}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Preparing for local late-pregnancy tests, appointments and shared decisions.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-36", slug: "pregnancy-week-36-early-labour-signs-and-readiness", title: "Pregnancy Week 36: Early Labour Signs and Readiness", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 36, "endWeek": 36}, format: "weekly_update", minSec: 120, maxSec: 240, description: "How to distinguish possible labour signs and follow the care team's contact plan.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-37", slug: "pregnancy-week-37-approaching-term-calmly", title: "Pregnancy Week 37: Approaching Term Calmly", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 37, "endWeek": 37}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Daily care, movement awareness, emotional preparation and care-team contact guidance.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-38", slug: "pregnancy-week-38-labour-readiness-without-pressure", title: "Pregnancy Week 38: Labour Readiness Without Pressure", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 38, "endWeek": 38}, format: "weekly_update", minSec: 120, maxSec: 240, description: "Preparing practically and emotionally while recognising that every timeline differs.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-39", slug: "pregnancy-week-39-due-dates-are-estimates", title: "Pregnancy Week 39: Due Dates Are Estimates", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 39, "endWeek": 39}, format: "weekly_update", minSec: 120, maxSec: 240, description: "What the due date means, daily wellbeing and questions for the next appointment.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "preg-week-40", slug: "pregnancy-week-40-next-steps-with-your-care-team", title: "Pregnancy Week 40: Next Steps With Your Care Team", category: "pregnancy_week_by_week", categoryLabel: "Week by week", journeys: ["pregnant"], timing: {"type": "gestational_week", "startWeek": 40, "endWeek": 40}, format: "weekly_update", minSec: 120, maxSec: 240, description: "A calm overview of monitoring, follow-up and shared decisions after the estimated due date.", safety: "clinical", actions: ["ask_aira", "weekly_check_in", "prepare_appointment", "save_video"], languages: ["en", "hi"] },
  { id: "symptom-nausea", slug: "nausea-and-vomiting-in-pregnancy", title: "Nausea and Vomiting in Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Common patterns, hydration, care-team conversations and signs needing assessment.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-fatigue", slug: "why-pregnancy-fatigue-can-feel-so-strong", title: "Why Pregnancy Fatigue Can Feel So Strong", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A mother-first explanation of fatigue, rest, daily planning and when to discuss testing.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-heartburn", slug: "heartburn-and-indigestion-during-pregnancy", title: "Heartburn and Indigestion During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Understanding common triggers and preparing safe questions for the care team.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-constipation", slug: "constipation-during-pregnancy", title: "Constipation During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Hydration, nutrition, movement and medication questions to discuss with a professional.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-back-pelvic-pain", slug: "back-and-pelvic-pain-during-pregnancy", title: "Back and Pelvic Pain During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Comfort, movement modifications and signs that require professional assessment.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-headache", slug: "headaches-during-pregnancy-what-to-notice", title: "Headaches During Pregnancy: What to Notice", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "Tracking severity and associated symptoms while identifying urgent warning signs.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "symptom-swelling", slug: "swelling-during-pregnancy-expected-or-urgent", title: "Swelling During Pregnancy: Expected or Urgent?", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "A clear distinction between common swelling and warning signs needing prompt care.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "symptom-sleep", slug: "sleep-problems-during-pregnancy", title: "Sleep Problems During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Positioning, routines, emotional wellbeing and questions for persistent sleep difficulty.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-breathlessness", slug: "breathlessness-during-pregnancy", title: "Breathlessness During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "Common experiences, pacing and signs that require urgent assessment.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "symptom-cramps", slug: "cramps-and-abdominal-discomfort-in-pregnancy", title: "Cramps and Abdominal Discomfort in Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "How to describe location, timing and severity to the care team.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "symptom-reduced-movement", slug: "reduced-fetal-movement-what-to-do", title: "Reduced Fetal Movement: What to Do", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "Immediate care-team contact guidance without delaying for AI reassurance.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "symptom-bleeding-fluid", slug: "bleeding-or-fluid-leakage-during-pregnancy", title: "Bleeding or Fluid Leakage During Pregnancy", category: "pregnancy_symptoms", categoryLabel: "Symptoms", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "A safety-first guide directing users to timely professional assessment.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "nutrition-balanced-plate", slug: "building-a-balanced-pregnancy-plate", title: "Building a Balanced Pregnancy Plate", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A flexible meal framework that respects culture, appetite, access and care-team advice.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-folate", slug: "folate-and-folic-acid-why-they-matter", title: "Folate and Folic Acid: Why They Matter", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A plain-language explainer covering food sources, supplements and professional guidance.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-iron", slug: "iron-haemoglobin-and-pregnancy-fatigue", title: "Iron, Haemoglobin and Pregnancy Fatigue", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Understanding iron needs, common test discussions and safe supplement guidance.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-protein", slug: "protein-during-pregnancy", title: "Protein During Pregnancy", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Practical plant and animal protein options without rigid meal rules.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-hydration", slug: "hydration-during-pregnancy", title: "Hydration During Pregnancy", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Simple hydration habits and signs of dehydration requiring attention.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-food-safety", slug: "food-safety-during-pregnancy", title: "Food Safety During Pregnancy", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Handling, storage and local guidance for foods with higher infection risk.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-vegetarian", slug: "vegetarian-and-vegan-pregnancy-nutrition", title: "Vegetarian and Vegan Pregnancy Nutrition", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Key nutrients and questions to review with a dietitian or maternity clinician.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-glucose", slug: "eating-well-with-gestational-diabetes-guidance", title: "Eating Well With Gestational Diabetes Guidance", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Supporting an individual clinical plan without offering generic treatment.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-nausea", slug: "eating-when-nausea-changes-your-appetite", title: "Eating When Nausea Changes Your Appetite", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Small practical options and warning signs for poor intake or dehydration.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "nutrition-postpartum", slug: "postpartum-nutrition-for-recovery", title: "Postpartum Nutrition for Recovery", category: "nutrition", categoryLabel: "Nutrition", journeys: ["trying", "pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Flexible nutrition and hydration support for recovery and feeding choices.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "movement-walking", slug: "walking-safely-during-pregnancy", title: "Walking Safely During Pregnancy", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A guided, adaptable walking session with clear stop signs.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "movement-pelvic-floor", slug: "pelvic-floor-awareness-in-pregnancy", title: "Pelvic-Floor Awareness in Pregnancy", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A physiotherapist-reviewed introduction to coordination rather than pressure or perfection.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "movement-posture", slug: "posture-and-back-comfort", title: "Posture and Back Comfort", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "Gentle position changes and daily movement ideas for common discomfort.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "movement-yoga", slug: "gentle-prenatal-yoga-flow", title: "Gentle Prenatal Yoga Flow", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A short trimester-appropriate sequence with modifications and stop guidance.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "wellness-breathing", slug: "two-minute-aira-breathing-reset", title: "Two-Minute Aira Breathing Reset", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A calming visual breathing session for moments of overwhelm.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "wellness-sleep", slug: "pregnancy-sleep-wind-down", title: "Pregnancy Sleep Wind-Down", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A short relaxation session using breath, body awareness and a calm voice.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "wellness-labour-breathing", slug: "breathing-practice-for-labour", title: "Breathing Practice for Labour", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A non-promissory practice session to include in broader birth preparation.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "movement-postpartum", slug: "gentle-postpartum-movement", title: "Gentle Postpartum Movement", category: "movement_and_wellness", categoryLabel: "Movement & wellness", journeys: ["pregnant", "postpartum"], timing: {"type": "on_demand"}, format: "guided_session", minSec: 90, maxSec: 240, description: "A recovery-sensitive introduction that adapts to birth experience and clinical advice.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-first-visit", slug: "preparing-for-the-first-prenatal-appointment", title: "Preparing for the First Prenatal Appointment", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Health history, medicines, questions and practical preparation.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-ultrasound", slug: "ultrasound-basics-what-it-can-and-cannot-show", title: "Ultrasound Basics: What It Can and Cannot Show", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A plain-language guide that avoids diagnosing or interpreting personal results.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-screening-diagnostic", slug: "screening-tests-versus-diagnostic-tests", title: "Screening Tests Versus Diagnostic Tests", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Understanding the difference and preparing for informed discussions.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-anatomy-scan", slug: "preparing-for-the-anatomy-scan", title: "Preparing for the Anatomy Scan", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Purpose, possible outcomes and useful questions for the care team.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-glucose-screening", slug: "understanding-pregnancy-glucose-screening", title: "Understanding Pregnancy Glucose Screening", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "What the screening is for and why local instructions should be followed.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-blood-pressure", slug: "blood-pressure-and-urine-checks-in-pregnancy", title: "Blood Pressure and Urine Checks in Pregnancy", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Why routine monitoring matters and which symptoms need urgent care.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "test-vaccination", slug: "vaccination-conversations-during-pregnancy", title: "Vaccination Conversations During Pregnancy", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "How to prepare for a local, individualised discussion with a clinician.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "appointment-copilot", slug: "how-to-prepare-better-questions-for-your-appointment", title: "How to Prepare Better Questions for Your Appointment", category: "tests_and_appointments", categoryLabel: "Tests & appointments", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Turning check-ins, symptoms and concerns into a concise visit agenda.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-true-false", slug: "possible-labour-understanding-the-signs", title: "Possible Labour: Understanding the Signs", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Contraction patterns, associated signs and when to contact the maternity unit.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-contractions", slug: "how-to-time-contractions", title: "How to Time Contractions", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A simple guided timer and the care team's contact thresholds.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-water-breaking", slug: "what-if-your-waters-break", title: "What If Your Waters Break?", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "What to notice, what to record and when to contact the maternity team.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "labour-hospital-bag", slug: "hospital-bag-checklist", title: "Hospital Bag Checklist", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A practical, editable checklist for mother, baby and support person.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-birth-plan", slug: "creating-flexible-birth-preferences", title: "Creating Flexible Birth Preferences", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Values, comfort, communication and alternatives without promising a specific birth.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-pain-relief", slug: "pain-relief-options-during-labour", title: "Pain-Relief Options During Labour", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A neutral overview for discussion with the local maternity team.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-induction", slug: "understanding-induction-of-labour", title: "Understanding Induction of Labour", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Why induction may be discussed, common stages and questions to ask.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-vaginal-birth", slug: "what-happens-during-vaginal-birth", title: "What Happens During Vaginal Birth?", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A clinically reviewed, non-graphic process overview.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-caesarean", slug: "what-happens-during-a-caesarean-birth", title: "What Happens During a Caesarean Birth?", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Preparation, the operating-room journey, recovery and partner expectations.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "labour-partner-role", slug: "how-a-birth-partner-can-help", title: "How a Birth Partner Can Help", category: "labour_and_delivery", categoryLabel: "Labour & delivery", journeys: ["pregnant"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Practical comfort, advocacy, communication and logistics.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-first-day", slug: "the-first-24-hours-after-birth", title: "The First 24 Hours After Birth", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Common checks, rest, feeding support and questions for the maternity team.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-vaginal-recovery", slug: "recovery-after-vaginal-birth", title: "Recovery After Vaginal Birth", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Comfort, bleeding, stitches, pelvic health and signs needing assessment.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-caesarean-recovery", slug: "recovery-after-a-caesarean-birth", title: "Recovery After a Caesarean Birth", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Mobility, wound care, pain discussions and urgent warning signs.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-bleeding", slug: "postpartum-bleeding-what-to-monitor", title: "Postpartum Bleeding: What to Monitor", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "A safety-first overview of expected changes and urgent bleeding signs.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
  { id: "postpartum-pelvic-floor", slug: "pelvic-floor-recovery-after-birth", title: "Pelvic-Floor Recovery After Birth", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Gentle awareness, recovery timelines and when to seek physiotherapy.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-mental-health", slug: "baby-blues-anxiety-and-postpartum-depression", title: "Baby Blues, Anxiety and Postpartum Depression", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Recognising emotional changes and finding professional support without stigma.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-rest-support", slug: "rest-sleep-and-asking-for-help", title: "Rest, Sleep and Asking for Help", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Practical partner and family support during early recovery.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "postpartum-checkup", slug: "preparing-for-your-postpartum-check-up", title: "Preparing for Your Postpartum Check-Up", category: "postpartum_recovery", categoryLabel: "Postpartum recovery", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Physical recovery, mental wellbeing, feeding, contraception and unanswered questions.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-feeding-cues", slug: "understanding-newborn-feeding-cues", title: "Understanding Newborn Feeding Cues", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Early hunger and fullness cues across feeding choices.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-latch-support", slug: "breastfeeding-latch-when-to-ask-for-help", title: "Breastfeeding Latch: When to Ask for Help", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A reviewed visual guide that encourages skilled feeding support.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-burping", slug: "burping-and-holding-a-newborn", title: "Burping and Holding a Newborn", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Gentle positions and signs of discomfort to discuss with a professional.", safety: "standard", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-diaper-cord", slug: "diapering-and-umbilical-cord-care", title: "Diapering and Umbilical Cord Care", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Clean, simple care steps based on local clinician guidance.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-safe-sleep", slug: "creating-a-safer-newborn-sleep-space", title: "Creating a Safer Newborn Sleep Space", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "A safety-focused setup using current local guidance.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-crying", slug: "understanding-newborn-crying", title: "Understanding Newborn Crying", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "explainer", minSec: 90, maxSec: 240, description: "Common reasons, calming approaches and caregiver coping.", safety: "clinical", actions: ["ask_aira", "save_video", "add_to_care_plan"], languages: ["en", "hi"] },
  { id: "newborn-urgent-signs", slug: "when-a-newborn-needs-urgent-medical-care", title: "When a Newborn Needs Urgent Medical Care", category: "newborn_care", categoryLabel: "Newborn care", journeys: ["postpartum"], timing: {"type": "on_demand"}, format: "safety_explainer", minSec: 90, maxSec: 240, description: "Clear signs directing parents to immediate professional help.", safety: "urgent", actions: ["contact_care_team", "open_emergency_profile", "save_video"], languages: ["en", "hi"] },
];

/** The week-by-week video whose gestational band covers `week`, if any. */
export function videoForWeek(week: number | null | undefined): VideoTopic | null {
  if (week == null) return null;
  return VIDEO_TOPICS.find(
    (v) => v.timing.type === "gestational_week"
      && v.timing.startWeek != null && v.timing.endWeek != null
      && week >= v.timing.startWeek && week <= v.timing.endWeek,
  ) ?? null;
}

/** Topics relevant to a journey stage. `exploring`/unknown gets the on-demand library. */
export function videosForJourney(journey: string | null | undefined): VideoTopic[] {
  if (journey === "trying" || journey === "pregnant" || journey === "postpartum") {
    return VIDEO_TOPICS.filter((v) => v.journeys.includes(journey));
  }
  return VIDEO_TOPICS.filter((v) => v.timing.type === "on_demand");
}

/** "2-4 min" style label from the recommended duration range. */
export function durationLabel(v: VideoTopic): string {
  const lo = Math.max(1, Math.round(v.minSec / 60));
  const hi = Math.max(lo, Math.round(v.maxSec / 60));
  return lo === hi ? `${lo} min` : `${lo}–${hi} min`;
}
