"""Storage adapter: one connection helper for the whole data layer, backed by
SQLite (default, dev) or Postgres (`DATABASE_URL`, prod). The HTTP surface and
all module SQL stay identical across backends.

Portability comes from (a) using `ON CONFLICT … DO UPDATE/NOTHING` everywhere
(supported by SQLite >= 3.24 and Postgres) instead of SQLite-only
`INSERT OR REPLACE/IGNORE`, and (b) a thin wrapper that rewrites `?` placeholders
to `%s` for psycopg. Modules keep their existing `?`-style SQL.

To run on Postgres:  pip install 'psycopg[binary]'  and set
    DATABASE_URL=postgresql://user:pass@host/db
"""
import sqlite3
import threading
from contextlib import contextmanager

from app import config

_DATABASE_URL = config.DATABASE_URL
IS_POSTGRES = config.IS_POSTGRES

# Shared SQLite file (kept next to this module) when no DATABASE_URL is set.
# Override with SQLITE_PATH for tests/hermetic runs or an alternate data dir.
SQLITE_PATH = config.SQLITE_PATH

# Auto-incrementing integer primary key, spelled for the active backend. SQLite
# wants AUTOINCREMENT, which Postgres rejects as a syntax error — so a module
# that hardcoded it would take the whole Postgres path down at CREATE TABLE.
# Modules splice this in instead, keeping one DDL string for both backends.
AUTOINC_PK = ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if IS_POSTGRES
              else "INTEGER PRIMARY KEY AUTOINCREMENT")


class _PGCursor:  # pragma: no cover
    """Wrap a psycopg cursor so `?` placeholders and `.fetchone/.fetchall` work
    exactly like the sqlite3 cursors the modules already use."""
    def __init__(self, cur):
        self._cur = cur

    def execute(self, sql, params=()):
        # Escape literal % (psycopg treats it as a format char) BEFORE turning our
        # `?` placeholders into `%s`. Our SQL is first-party/static, so this is safe.
        self._cur.execute(sql.replace("%", "%%").replace("?", "%s"), params)
        return self

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def __iter__(self):
        return iter(self._cur)

    @property
    def rowcount(self):
        return self._cur.rowcount


class _PGConn:  # pragma: no cover
    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=()):
        cur = _PGCursor(self._raw.cursor())
        return cur.execute(sql, params)

    def commit(self):
        self._raw.commit()

    @contextmanager
    def transaction(self):
        with self._raw.transaction():
            yield


class _ThreadLocalConn:
    """A connection handle that transparently gives each thread its OWN real DB
    connection to the same database.

    The HTTP layer runs every handler in `asyncio.to_thread` (real OS threads),
    so a single shared connection would have multiple threads interleaving
    cursors and commits. Instead each thread lazily opens its own connection on
    first use; SQLite WAL + busy_timeout lets those per-thread connections
    read/write the same file concurrently, and the Postgres path gets one
    autocommit connection per thread. Call sites keep using
    `.execute(...).fetchone()/.fetchall()` and `.commit()` unchanged."""

    def __init__(self, opener):
        self._opener = opener
        self._local = threading.local()

    def _conn(self):
        c = getattr(self._local, "conn", None)
        if c is None:
            c = self._opener()
            self._local.conn = c
        return c

    def execute(self, sql, params=()):
        return self._conn().execute(sql, params)

    def commit(self):
        self._conn().commit()

    @contextmanager
    def transaction(self):
        """Make a batch of writes atomic on either backend: everything in the
        block commits together, or rolls back if the block raises. Each thread
        holds its own connection, so this never interleaves with another
        thread's transaction."""
        c = self._conn()
        pg_tx = getattr(c, "transaction", None)
        if pg_tx is not None:  # _PGConn (Postgres)
            with pg_tx():
                yield self
        else:  # sqlite3.Connection: `with conn` commits, or rolls back on error
            with c:
                yield self


def _open_sqlite(path: str):
    conn = sqlite3.connect(path, check_same_thread=False)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA busy_timeout=3000")
    return conn


def connect(sqlite_path: str | None = None):
    """Open a connection appropriate for the configured backend. Returns a
    thread-safe handle exposing the `.execute/.fetchone/.fetchall/.commit`
    subset every module uses, handing each thread its own underlying connection
    so concurrent handlers can't corrupt one another's cursors."""
    if IS_POSTGRES:
        def _open_pg():
            import psycopg  # lazy: only needed in the Postgres deployment
            return _PGConn(psycopg.connect(_DATABASE_URL, autocommit=True))
        return _ThreadLocalConn(_open_pg)
    path = sqlite_path or SQLITE_PATH
    return _ThreadLocalConn(lambda: _open_sqlite(path))


def like_param(term: str) -> str:
    """Escape a user-supplied search term for a case-insensitive
    `LOWER(col) LIKE ? ESCAPE '\\'` match. Portable SQLite/Postgres."""
    t = (term or "").strip().lower()
    t = t.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
    return f"%{t}%"
